languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "app/assets/javascripts/wickedpicker.js"
- "app/assets/stylesheets/wickedpicker.css"
- "app/assets/stylesheets/foundation-datepicker.css"
- "/app/public"
