# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2acd9d2deb3134cd2ac186e518e42c2d5974222cce9cd5af6d4c227fc38b02f3c97145868f0a8fd89a5f10c463d7479a98d201bf3bcb2b23b6475a31433d1d0

test:
  secret_key_base: a1fb949126db2e1846a91db3e1055c9ca849e2d781df5f4c34a2a4a4a9e944d3b81faa3951f0bea71bbfa453cec000245de022927e237a3efafe6a925ca8d0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
